#!/bin/sh

# ref: https://gitlab.com/postmarketOS/pmaports/-/blob/master/main/postmarketos-mkinitfs/init_functions.sh

VENDOR_ID="0x18d1"
PRODUCT_ID="0xd00d"

ANDROID_USB=/sys/class/android_usb/android0
echo 0 > $ANDROID_USB/enable
echo $VENDOR_ID > $ANDROID_USB/idVendor
echo $PRODUCT_ID > $ANDROID_USB/idProduct
echo 'rndis' > $ANDROID_USB/functions
echo 1 > $ANDROID_USB/enable
CONFIGFS=/config/usb_gadget
mkdir -pv $CONFIGFS/g1
echo $VENDOR_ID > $CONFIGFS/g1/idVendor
echo $PRODUCT_ID > $CONFIGFS/g1/idProduct
mkdir -pv $CONFIGFS/g1/strings/0x409
echo "xiaomi" > $CONFIGFS/g1/strings/0x409/manufacturer
echo "buildroot" > $CONFIGFS/g1/strings/0x409/serialnumber
echo "redmi8a" > $CONFIGFS/g1/strings/0x409/product
mkdir -pv $CONFIGFS/g1/functions/rndis.usb0
mkdir -pv $CONFIGFS/g1/configs/c.1
mkdir -pv $CONFIGFS/g1/configs/c.1/strings/0x409
echo 'rndis' > $CONFIGFS/g1/configs/c.1/strings/0x409/configuration
ln -sv $CONFIGFS/g1/functions/rndis.usb0 $CONFIGFS/g1/configs/c.1
ls /sys/class/udc > $CONFIGFS/g1/UDC
ifconfig rndis0 up
ifconfig usb0 up
ifconfig rndis0 192.168.200.1/24
ifconfig usb0 192.168.200.1/24
exit 0
