#!/bin/sh

LOG_FILE=/mnt/log/$(date +%Y%m%d).log
# collect info
mkdir -p /mnt/log
mount -t vfat /dev/block/mmcblk1p1 /mnt/log
du / >> $LOG_FILE
ps aux >> $LOG_FILE
ifconfig >> $LOG_FILE
ip link >> $LOG_FILE
lsmod >> $LOG_FILE
dmesg >> $LOG_FILE
umount /dev/block/mmcblk1p1
exit 0
